-- =========================================================
-- SWASTHYA SETU — IDENTITY ARCHITECTURE MIGRATION
-- Production-ready patient identity, verification, and audit
-- =========================================================

-- Enable UUID generation if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 1. patients — Internal patient records
-- =============================================
CREATE TABLE IF NOT EXISTS patients (
  patient_id              VARCHAR(20) PRIMARY KEY,
  first_name              VARCHAR(100),
  middle_name             VARCHAR(100),
  last_name               VARCHAR(100),
  name                    VARCHAR(200) NOT NULL,
  date_of_birth           DATE,
  age                     INT,
  gender                  VARCHAR(10),
  mobile                  VARCHAR(15),
  mobile_verified         BOOLEAN DEFAULT false,
  mobile_verified_at      TIMESTAMPTZ,
  email                   VARCHAR(150),
  blood_group             VARCHAR(10),
  password_hash           VARCHAR(200),
  pin_hash                VARCHAR(200),
  profile_status          VARCHAR(20) DEFAULT 'ACTIVE',
  profile_source          VARCHAR(30) DEFAULT 'MANUAL',
  abha_id                 VARCHAR(30),
  village                 VARCHAR(150),
  permanent_address_completed BOOLEAN DEFAULT false,
  created_at              TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at              TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE patients IS 'Internal Swasthya Setu patient records. patient_id is the primary identifier — NOT mobile, ABHA, or Aadhaar.';
COMMENT ON COLUMN patients.patient_id IS 'Format: PT-XXXXXX. Generated from patient_id_seq sequence.';
COMMENT ON COLUMN patients.profile_source IS 'MANUAL | MOBILE_VERIFICATION | ABHA | ABDM | AADHAAR | AUTHORIZED_EKYC | LEGACY_MIGRATION';
COMMENT ON COLUMN patients.profile_status IS 'ACTIVE | INACTIVE | SUSPENDED | PENDING_VERIFICATION';

-- =============================================
-- 2. patient_identities — External identity links
-- =============================================
CREATE TABLE IF NOT EXISTS patient_identities (
  id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id              VARCHAR(20) NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
  identity_type           VARCHAR(20) NOT NULL,
  external_reference      VARCHAR(100) NOT NULL,
  verification_status     VARCHAR(20) DEFAULT 'UNVERIFIED' NOT NULL,
  verified_at             TIMESTAMPTZ,
  source                  VARCHAR(30),
  metadata                JSONB DEFAULT '{}'::jsonb,
  created_at              TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at              TIMESTAMPTZ DEFAULT now() NOT NULL,
  UNIQUE(patient_id, identity_type, external_reference)
);

COMMENT ON TABLE patient_identities IS 'Links external identifiers (Mobile, ABHA, Aadhaar) to internal patient_id.';
COMMENT ON COLUMN patient_identities.identity_type IS 'MOBILE | ABHA | AADHAAR';
COMMENT ON COLUMN patient_identities.verification_status IS 'UNVERIFIED | PENDING | VERIFIED | FAILED | EXPIRED | REVOKED';
COMMENT ON COLUMN patient_identities.external_reference IS 'Verified mobile number, ABHA reference, or masked Aadhaar token. NEVER store raw Aadhaar number.';
COMMENT ON COLUMN patient_identities.source IS 'MANUAL | MOBILE_VERIFICATION | ABHA | ABDM | AADHAAR | AUTHORIZED_EKYC | LEGACY_AUTOGENERATED';

CREATE INDEX IF NOT EXISTS idx_patient_identities_patient_id ON patient_identities(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_identities_type_ref ON patient_identities(identity_type, external_reference);
CREATE INDEX IF NOT EXISTS idx_patient_identities_status ON patient_identities(verification_status);

-- =============================================
-- 3. patient_addresses_v2 — Structured addresses
-- =============================================
CREATE TABLE IF NOT EXISTS patient_addresses_v2 (
  id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id              VARCHAR(20) NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
  address_type            VARCHAR(20) DEFAULT 'PERMANENT',
  address_line_1          VARCHAR(200),
  address_line_2          VARCHAR(200),
  landmark                VARCHAR(150),
  country                 VARCHAR(50) DEFAULT 'India',
  state                   VARCHAR(100),
  district                VARCHAR(100),
  mandal                  VARCHAR(100),
  village_city            VARCHAR(100),
  pincode                 VARCHAR(10),
  source                  VARCHAR(30) DEFAULT 'PATIENT_PROVIDED',
  created_at              TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at              TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE patient_addresses_v2 IS 'Structured patient addresses with source tracking.';
COMMENT ON COLUMN patient_addresses_v2.source IS 'PATIENT_PROVIDED | VERIFIED_FROM_AUTHORIZED_SOURCE | ABHA | AADHAAR';

CREATE INDEX IF NOT EXISTS idx_patient_addresses_v2_patient_id ON patient_addresses_v2(patient_id);

-- =============================================
-- 4. otp_requests — Server-side OTP tracking
-- =============================================
CREATE TABLE IF NOT EXISTS otp_requests (
  id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  mobile                  VARCHAR(15) NOT NULL,
  otp_hash                VARCHAR(200) NOT NULL,
  purpose                 VARCHAR(30) NOT NULL,
  attempts                INT DEFAULT 0,
  max_attempts            INT DEFAULT 3,
  expires_at              TIMESTAMPTZ NOT NULL,
  used                    BOOLEAN DEFAULT false,
  used_at                 TIMESTAMPTZ,
  patient_id              VARCHAR(20),
  request_ip              VARCHAR(45),
  created_at              TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE otp_requests IS 'Tracks OTP requests server-side. OTP stored as bcrypt hash — NEVER in plaintext.';
COMMENT ON COLUMN otp_requests.otp_hash IS 'bcrypt hash of the 6-digit OTP. Raw OTP is NEVER stored.';
COMMENT ON COLUMN otp_requests.purpose IS 'REGISTRATION | FORGOT_PASSWORD | MOBILE_VERIFY | LOGIN_VERIFY';

CREATE INDEX IF NOT EXISTS idx_otp_requests_mobile_purpose ON otp_requests(mobile, purpose);
CREATE INDEX IF NOT EXISTS idx_otp_requests_expires ON otp_requests(expires_at);

-- =============================================
-- 5. identity_audit_log — Immutable audit trail
-- =============================================
CREATE TABLE IF NOT EXISTS identity_audit_log (
  id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id              VARCHAR(20),
  action                  VARCHAR(50) NOT NULL,
  identity_type           VARCHAR(20),
  status                  VARCHAR(20),
  request_id              VARCHAR(50),
  admin_id                VARCHAR(20),
  ip_address              VARCHAR(45),
  details                 JSONB DEFAULT '{}'::jsonb,
  created_at              TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE identity_audit_log IS 'Immutable audit trail for identity operations. NEVER contains OTPs, passwords, PID data, biometric info, or secrets.';

CREATE INDEX IF NOT EXISTS idx_audit_log_patient_id ON identity_audit_log(patient_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON identity_audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON identity_audit_log(created_at);

-- =============================================
-- 6. Patient ID sequence
-- =============================================
CREATE SEQUENCE IF NOT EXISTS patient_id_seq START WITH 1000 INCREMENT BY 1;

-- =============================================
-- 7. Backward-compatible additions to existing profiles table
-- =============================================
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'profiles' AND table_schema = 'public') THEN
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS patient_id VARCHAR(20);
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mobile_verified BOOLEAN DEFAULT false;
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mobile_verified_at TIMESTAMPTZ;
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profile_source VARCHAR(30) DEFAULT 'MANUAL';
  END IF;
END
$$;

-- =============================================
-- 8. Row-Level Security (RLS) policies
-- =============================================

-- Enable RLS on sensitive tables
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE otp_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity_audit_log ENABLE ROW LEVEL SECURITY;

-- Service role has full access (for backend server)
CREATE POLICY IF NOT EXISTS "Service role full access on patients"
  ON patients FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Service role full access on patient_identities"
  ON patient_identities FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Service role full access on otp_requests"
  ON otp_requests FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Service role full access on identity_audit_log"
  ON identity_audit_log FOR ALL
  USING (true)
  WITH CHECK (true);
